/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["src/**/*.html"],
  theme: {
    extend: {
      colors: {
        secondary: "#bbc9d0",
        "primary-container": "#00baff",
        "outline-variant": "#3d4850",
        "on-background": "#d6e3ff",
        "on-surface": "#d6e3ff",
        "surface-dim": "#00132e",
        "on-tertiary": "#4a2800",
        "surface-container-low": "#001b3d",
        primary: "#8ad2ff",
        "on-primary": "#00344b",
        "on-tertiary-fixed-variant": "#6a3c00",
        "on-primary-container": "#004764",
        "primary-fixed-dim": "#81cfff",
        "surface-container-high": "#0b2a50",
        "error-container": "#93000a",
        "surface-tint": "#81cfff",
        "tertiary-fixed-dim": "#ffb871",
        "secondary-fixed-dim": "#bbc9d0",
        "surface-bright": "#1f3960",
        "on-primary-fixed": "#001e2d",
        surface: "#00132e",
        outline: "#87929b",
        "tertiary-container": "#f8971f",
        "on-tertiary-container": "#623700",
        "surface-container-highest": "#19355c",
        "inverse-on-surface": "#143057",
        "primary-fixed": "#c6e7ff",
        "on-secondary-fixed-variant": "#3c494f",
        "tertiary-fixed": "#ffdcbe",
        "surface-variant": "#19355c",
        error: "#ffb4ab",
        "on-secondary-container": "#adbbc2",
        tertiary: "#ffbc7a",
        "on-error-container": "#ffdad6",
        "surface-container": "#001f44",
        "on-secondary-fixed": "#101d23",
        "on-error": "#690005",
        "on-secondary": "#253238",
        "on-surface-variant": "#bdc8d2",
        background: "#00132e",
        "surface-container-lowest": "#000e24",
        "inverse-surface": "#d6e3ff",
        "on-primary-fixed-variant": "#004c6b",
        "secondary-fixed": "#d7e5ec",
        "secondary-container": "#3e4b51",
        "inverse-primary": "#00658d",
        "on-tertiary-fixed": "#2d1600",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Work Sans", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
    },
  },
  plugins: [],
};
